# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{relaxed-job}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Dollar"]
  s.date = %q{2009-11-09}
  s.description = %q{Relaxed Job}
  s.email = %q{<ddollar@gmail.com>}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/relaxed-job.rb",
     "lib/relaxed_job.rb",
     "lib/relaxed_job/designs/jobs/views/completed/map.js",
     "lib/relaxed_job/designs/jobs/views/errored/map.js",
     "lib/relaxed_job/designs/jobs/views/locked/map.js",
     "lib/relaxed_job/designs/jobs/views/pending/map.js",
     "lib/relaxed_job/queue.rb",
     "lib/relaxed_job/tasks.rb",
     "lib/relaxed_job/worker.rb",
     "spec/rcov.opts",
     "spec/relaxed_job/queue_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/ddollar/relaxed-job}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Relaxed Job}
  s.test_files = [
    "spec/relaxed_job/queue_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_runtime_dependency(%q<couchrest>, [">= 0"])
      s.add_runtime_dependency(%q<libdir>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<couchrest>, [">= 0"])
      s.add_dependency(%q<libdir>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<couchrest>, [">= 0"])
    s.add_dependency(%q<libdir>, [">= 0"])
  end
end
